# Generated by Django 3.2.9 on 2021-12-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='body',
            field=models.JSONField(),
        ),
    ]
