# Generated by Django 3.2.9 on 2021-12-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_script_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
