# Generated by Django 3.2.9 on 2022-03-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filestore',
            field=models.FileField(upload_to='files'),
        ),
    ]
